export enum OrderType {
    CV = 'CV',
    COVER_LETTER = 'COVER LETTER',
    LINKEDIN = 'LINKEDIN',
    ROADMAP = 'ROADMAP',
    INTERVIEW_PREPARATION = 'INTERVIEW PREPARATION',
    CAREER_PLAN = 'CAREER PLAN'
}